AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.1
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'bin/*'
    - 'config/**/*'
    - 'node_modules/**/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space # default is space

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
